### ISSUE TITLE
about downloading latest image 

### ISSUE THREAD

**Issue by willllllllllllll** [uptane/uptane-standard#88] opened 2019-03-21 07:25 UTC
From on the latest standard, I cannot find out the strategy for primary ECU to select source of storage for downloading images. Based on the demo code, the new image file for ECU is added to both repositories. Which repository should be selected, image repo or director repo? or both repositories share the same image file storage?
Is it possible to add some clear description to address this concern?

**Comment by JustinCappos** [comment] 2019-03-21 11:52
We'll clarify.  The actual location of the image that is downloaded may come from anywhere (director repo, image repo, CDN, etc.)  It seems most likely that an image repo or a CDN would be used in practice.

The director and image repository metadata MUST both contain the secure hash of the image, however.

**Comment by tkfu** [comment] 2019-03-27 15:31
Closed--dupe of #53

**Comment by trishankatdatadog** [comment] 2019-03-27 15:31
I think this is related to #53, will clarify, thanks

**Closed** 2019-03-27 15:31 UTC

**Comment by jhdalek55** [comment] 2019-03-27 17:55
On the 3/27 standards call, @trishankatdatadog noted that this was related to Issue #53. This issue was closed as it will be addressed in the response to #53.
